Repository pknu-wap/OverClean, pull requests merged in 2024-11, with the labels that each got.

#95 [Fix] 룸 온라인 기능 픽스 / 구현
  Assets/Scenes/RoomScene.unity
  Assets/Script/NetworkingManager.cs
  Assets/Script/RoomManager.cs
  ProjectSettings/Packages/com.unity.testtools.codecoverage/Settings.json
Labels: 👾버그잡기👾, ✨기능구현✨, 🌟리뷰해주세요🌟, 🧐도현석🧐, 🗿고혁빈🗿, ✅ 완료

#99 [Feature] 시작 파이프부터 종료 파이프까지의 연결 확인 함수 구현
  Assets/Scenes/PuzzleScene/PrisonPuzzleScene/PrisonPipePuzzleScene.unity
  Assets/Script/PrisonSceneScript/PrisonPuzzleScript/PrisonPuzzle_PipeScript/PipeTileScript.cs
  Assets/Script/PrisonSceneScript/PrisonPuzzleScript/PrisonPuzzle_PipeScript/PrisonPipePuzzleScript.cs
  Assets/Sprites/TmpPipeTileSprite/PipeTileLShape.png
  Assets/Sprites/TmpPipeTileSprite/PipeTileStraightShape.png
  Assets/Sprites/TmpPipeTileSprite/PipeTileTShape.png
Labels: ✨기능구현✨, 🌟리뷰해주세요🌟, 🤓박준우🤓, 🎨이진우🎨, ✅ 완료

#103 [Feature] 퍼즐창 뒤로가기 버튼 구현
  Assets/Images/backButton.png
  Assets/Images/backButton.png.meta
  Assets/Scenes/PrisonScene.unity
  Assets/Scenes/PuzzleScene/PrisonPuzzleScene/PrisonDoorPuzzleScene.unity
  Assets/Scenes/PuzzleScene/PrisonPuzzleScene/PrisonDustPuzzleScene.unity
  Assets/Scenes/PuzzleScene/PrisonPuzzleScene/PrisonLeafPuzzleScene.unity
  Assets/Scenes/PuzzleScene/PrisonPuzzleScene/PrisonPipePuzzleScene.unity
  Assets/Script/PlayerManager.cs
  Assets/Script/PrisonSceneScript/PrisonInteractScript/DoorInteractScript.cs
  Assets/Script/PrisonSceneScript/PrisonInteractScript/DustInteractScript.cs
  Assets/Script/PrisonSceneScript/PrisonInteractScript/LeafInteractScript.cs
  Assets/Script/PrisonSceneScript/PrisonInteractScript/PipeInteractScript.cs
  Assets/Script/PrisonSceneScript/PrisonPuzzleScript/PrisonPuzzle_DoorScript/PrisonDoorPuzzleScript.cs
  Assets/Script/PrisonSceneScript/PrisonPuzzleScript/PrisonPuzzle_LeafDustScript/PrisonDustLeafPuzzleScript.cs
  Assets/Script/PrisonSceneScript/PrisonPuzzleScript/PrisonPuzzle_PipeScript/PrisonPipePuzzleScript.cs
  Assets/Script/PuzzleManager.cs
  Assets/Script/StageManagerScript.cs
Labels: ✨기능구현✨, 🎨이진우🎨, ✅ 완료

#102 [Feature] 튜토리얼 클리어시 모달창 띄우기
  Assets/Scenes/PrisonScene.unity
  Assets/Scenes/TitleScene.unity
  Assets/Script/GoalZoneScript.cs
  Assets/Script/NetworkingManager.cs
  Assets/Script/StageManagerScript.cs
Labels: ✨기능구현✨, 🎨이진우🎨, ✅ 완료

#105 [Feature] ESC누르면 설정창 나오게 구현
  Assets/Scenes/PrisonScene.unity
  Assets/Script/StageManagerScript.cs
Labels: ✨기능구현✨, 🎨이진우🎨, ✅ 완료

#104 [Feature] 성공을 보장하는 파이프 길 생성 함수 구현
  Assets/Scenes/PrisonScene.unity
  Assets/Scenes/PuzzleScene/PrisonPuzzleScene/PrisonPipePuzzleScene.unity
  Assets/Script/PrisonSceneScript/PrisonPuzzleScript/PrisonPuzzle_PipeScript/PrisonPipePuzzleScript.cs
Labels: ✨기능구현✨, 🌟리뷰해주세요🌟, 🤓박준우🤓, ✅ 완료

#111 [Feature] 네트워크 동기화 : 플레이어 이동 동기화
  Assets/Photon/PhotonUnityNetworking/Resources/PhotonServerSettings.asset
  Assets/Resources/Player1.prefab
  Assets/Resources/Player1.prefab.meta
  Assets/Resources/Player2.prefab
  Assets/Resources/Player2.prefab.meta
  Assets/Scenes/PrisonScene.unity
  Assets/Script/NetworkingManager.cs
  Assets/Script/PlayerManager.cs
  Assets/Script/PrisonSceneScript/PrisonInteractScript/DoorInteractScript.cs
  Assets/Script/RoomManager.cs
  Assets/Script/StageManagerScript.cs
Labels: ✨기능구현✨, 🌟리뷰해주세요🌟, 🧐도현석🧐, ✅ 완료

#115 [Feature] 주택 씬에 들어가면 달리기키가 존재 한다고 모달창이 뜸
  Assets/Images/ShiftKeyButton.png
  Assets/Images/ShiftKeyButton.png.meta
  Assets/Scenes/HouseScene.unity
Labels: ✨기능구현✨, 🎨이진우🎨, ✅ 완료

#117 [Fix] 이전 merge에서 일어났던 오류 수정
  Assets/Scenes/PrisonScene.unity
  Assets/Scenes/PrisonScene.unity.meta
  Assets/Script/PrisonSceneScript/PrisonInteractScript/DoorInteractScript.cs
  Assets/Script/StageManagerScript.cs
  ProjectSettings/EditorBuildSettings.asset
Labels: 👾버그잡기👾, 🌟리뷰해주세요🌟, 😖잡일😖, 🗿고혁빈🗿, ✅ 완료

#119 [Featrue] 게임 시작시 카운트 다운 텍스트 구현
  Assets/Plugins/ParrelSync.meta
  Assets/Plugins/ParrelSync/ScriptableObjects.meta
  Assets/Plugins/ParrelSync/ScriptableObjects/ParrelSyncProjectSettings.asset
  Assets/Plugins/ParrelSync/ScriptableObjects/ParrelSyncProjectSettings.asset.meta
  Assets/Scenes/RoomScene.unity
  Assets/Script/RoomManager.cs
  Packages/manifest.json
  Packages/packages-lock.json
Labels: ✨기능구현✨, 🎨이진우🎨, ✅ 완료

#112 [Feature] 주택 씬에서, Shift 눌렀을때 달리기 구현
  Assets/Scenes/PrisonScene.unity
  Assets/Script/PlayerManager.cs
Labels: ✨기능구현✨, 🎨이진우🎨, ✅ 완료

#123 [Feature] 문 퍼즐 네트워킹 동기화 구현
  Assets/Photon/PhotonUnityNetworking/Resources/PhotonServerSettings.asset
  Assets/Scenes/PrisonScene.unity
  Assets/Scenes/PuzzleScene/PrisonPuzzleScene/PrisonDoorPuzzleScene.unity
  Assets/Script/LayerSortZoneScript.cs
  Assets/Script/PrisonSceneScript/PrisonInteractScript/DoorInteractScript.cs
  Assets/Script/PrisonSceneScript/PrisonInteractScript/DustInteractScript.cs
  Assets/Script/PrisonSceneScript/PrisonInteractScript/LeafInteractScript.cs
  Assets/Script/PrisonSceneScript/PrisonInteractScript/PipeInteractScript.cs
  Assets/Script/PrisonSceneScript/PrisonPuzzleScript/PrisonPuzzle_DoorScript/PrisonDoorPuzzleScript.cs
  Assets/Script/PrisonSceneScript/PrisonPuzzleScript/PrisonPuzzle_LeafDustScript/PrisonDustLeafPuzzleScript.cs
  Assets/Script/PrisonSceneScript/PrisonPuzzleScript/PrisonPuzzle_PipeScript/PrisonPipePuzzleScript.cs
  Assets/Script/PuzzleManager.cs
  Assets/Sprites/Square.png
  Assets/Sprites/Square.png.meta
Labels: ✨기능구현✨, 🌟리뷰해주세요🌟, 🗿고혁빈🗿, ✅ 완료

#127 [Feature] 감옥 퍼즐 네트워크 동기화 구현
  Assets/Photon/PhotonUnityNetworking/Resources/PhotonServerSettings.asset
  Assets/Scenes/PrisonScene.unity
  Assets/Scenes/PuzzleScene/PrisonPuzzleScene/PrisonPipePuzzleScene.unity
  Assets/Script/PlayerManager.cs
  Assets/Script/PrisonSceneScript/PrisonInteractScript/DoorInteractScript.cs
  Assets/Script/PrisonSceneScript/PrisonInteractScript/DustInteractScript.cs
  Assets/Script/PrisonSceneScript/PrisonInteractScript/LeafInteractScript.cs
  Assets/Script/PrisonSceneScript/PrisonInteractScript/PipeInteractScript.cs
  Assets/Script/PrisonSceneScript/PrisonPuzzleScript/PrisonPuzzle_PipeScript/PrisonPipePuzzleScript.cs
  Assets/Sprites/ColliderTileImage/ColliderLShape.png.meta
Labels: ✨기능구현✨, 🌟리뷰해주세요🌟, 🗿고혁빈🗿, ✅ 완료

#124 [Feature] 튜토리얼 모달창 네트워크 적용
  Assets/Scenes/PrisonScene.unity
  Assets/Script/PlayerManager.cs
  Assets/Script/StageManagerScript.cs
  Assets/Script/UIManager.cs
  Assets/TextMesh Pro/Resources/Fonts & Materials/LiberationSans SDF - Fallback.asset
Labels: ✨기능구현✨, 🎨이진우🎨, ✅ 완료

#129 [Refactor] 버튼 눌러서 UI 관련된 기능 UIManager로 옮기기
  Assets/Scenes/LobbyScene.unity
  Assets/Scenes/PrisonScene.unity
  Assets/Scenes/TitleScene.unity
  Assets/Script/NetworkingManager.cs
  Assets/Script/StageManagerScript.cs
  Assets/Script/UIManager.cs
Labels: 🌟리뷰해주세요🌟, 🎨이진우🎨, 🎨스타일수정🎨, ✅ 완료

#121 [Feature] 파이프 퍼즐 연결 검사 타이밍 변경
  Assets/Scenes/PuzzleScene/PrisonPuzzleScene/PrisonPipePuzzleScene.unity
  Assets/Script/PrisonSceneScript/PrisonPuzzleScript/PrisonPuzzle_PipeScript/PipeTileScript.cs
  Assets/Script/PrisonSceneScript/PrisonPuzzleScript/PrisonPuzzle_PipeScript/PrisonPipePuzzleScript.cs
Labels: ✨기능구현✨, 🌟리뷰해주세요🌟, 🤓박준우🤓, ✅ 완료

#134 [Fix] 뒤로가기 버튼 - 이동 제어 로직 픽스
  Assets/Photon/PhotonUnityNetworking/Resources/PhotonServerSettings.asset
  Assets/Scenes/PrisonScene.unity
  Assets/Script/PrisonSceneScript/PrisonInteractScript/DoorInteractScript.cs
  Assets/Script/PrisonSceneScript/PrisonInteractScript/DustInteractScript.cs
  Assets/Script/PrisonSceneScript/PrisonInteractScript/LeafInteractScript.cs
  Assets/Script/PrisonSceneScript/PrisonInteractScript/PipeInteractScript.cs
  Assets/Script/PrisonSceneScript/PrisonPuzzleScript/PrisonPuzzle_DoorScript/PrisonDoorPuzzleScript.cs
  Assets/Script/PrisonSceneScript/PrisonPuzzleScript/PrisonPuzzle_LeafDustScript/PrisonDustLeafPuzzleScript.cs
  Assets/Script/PrisonSceneScript/PrisonPuzzleScript/PrisonPuzzle_PipeScript/PrisonPipePuzzleScript.cs
  Assets/Script/PuzzleManager.cs
Labels: 👾버그잡기👾, ✨기능구현✨, 🌟리뷰해주세요🌟, 🗿고혁빈🗿, ✅ 완료

#135 [Feature] 파이프 퍼즐 네트워크 동기화 구현
  .vsconfig
  Assets/Photon/PhotonUnityNetworking/Resources/PhotonServerSettings.asset
  Assets/Resources/PipeTileLShape.png
  Assets/Resources/PipeTileLShape.png.meta
  Assets/Resources/PipeTileLshape.prefab
  Assets/Resources/PipeTileLshape.prefab.meta
  Assets/Resources/PipeTileStraightShape.png
  Assets/Resources/PipeTileStraightShape.png.meta
  Assets/Resources/PipeTileStraightShape.prefab
  Assets/Resources/PipeTileStraightShape.prefab.meta
  Assets/Resources/PipeTileTShape.png
  Assets/Resources/PipeTileTShape.png.meta
  Assets/Resources/PipeTileTShape.prefab
  Assets/Resources/PipeTileTShape.prefab.meta
  Assets/Script/PlayerManager.cs
  Assets/Script/PrisonSceneScript/PrisonPuzzleScript/PrisonPuzzle_PipeScript/PipeTileScript.cs
  Assets/Script/PrisonSceneScript/PrisonPuzzleScript/PrisonPuzzle_PipeScript/PrisonPipePuzzleScript.cs
Labels: ✨기능구현✨, 🌟리뷰해주세요🌟, 🧐도현석🧐, 🗿고혁빈🗿, ✅ 완료

#141 [Feature] 게임 클리어 & 일시정지 모달창 네트워크 동기화
  Assets/Photon/PhotonUnityNetworking/Resources/PhotonServerSettings.asset
  Assets/Scenes/PrisonScene.unity
  Assets/Script/GoalZoneScript.cs
  Assets/Script/LobbyManager.cs
  Assets/Script/PlayerManager.cs
  Assets/Script/StageManagerScript.cs
  Assets/Script/UIManager.cs
Labels: ✨기능구현✨, 🗿고혁빈🗿, 🎨이진우🎨, ✅ 완료

#145 [Feature] 주택-일시정지 모달창 적용
  Assets/Photon/PhotonUnityNetworking/Resources/PhotonServerSettings.asset
  Assets/Scenes/HouseScene.unity
  Assets/Scenes/LobbyScene.unity
  Assets/Scenes/PrisonScene.unity
  Assets/Scenes/TitleScene.unity
  Assets/Script/LobbyManager.cs
  Assets/Script/RoomManager.cs
  Assets/Script/UIManager.cs
  Assets/Script/UIManager.meta
  Assets/Script/UIManager/HouseUIManager.cs
  Assets/Script/UIManager/HouseUIManager.cs.meta
  Assets/Script/UIManager/LobbyUIManager.cs
  Assets/Script/UIManager/LobbyUIManager.cs.meta
  Assets/Script/UIManager/PrisonUIManager.cs
  Assets/Script/UIManager/PrisonUIManager.cs.meta
  Assets/Script/UIManager/TitleUIManager.cs
  Assets/Script/UIManager/TitleUIManager.cs.meta
  ProjectSettings/ProjectSettings.asset
Labels: ✨기능구현✨, 🎨이진우🎨, ✅ 완료

#147 [Fix] 스테이지 클리어 로직 수정
  Assets/Scenes/PrisonScene.unity
  Assets/Script/GoalZoneScript.cs
  Assets/Script/StageManagerScript.cs
Labels: 👾버그잡기👾, ✨기능구현✨, 🌟리뷰해주세요🌟, 🗿고혁빈🗿, ✅ 완료

#153 [Feature] 주택-게임클리어 모달창 적용
  Assets/Scenes/HouseScene.unity
  ProjectSettings/ProjectSettings.asset
Labels: ✨기능구현✨, 🎨이진우🎨, ✅ 완료

#140 [Docs] README.md 업데이트
  README.md
Labels: 📝문서📝, 🧐도현석🧐, ▶️ 진행 중

#156 [Chore] 이미지 디자인 적용
  Assets/Scenes/LobbyScene.unity
  Assets/Scenes/RoomScene.unity
  Assets/Scenes/TitleScene.unity
Labels: 🌟리뷰해주세요🌟, 🎨이진우🎨, 🎨스타일수정🎨, ✅ 완료

#155 [Fix] #150에서 잡지 못한 버그 픽스
  Assets/Resources/Player1.prefab
  Assets/Resources/Player2.prefab
  Assets/Scenes/HouseScene.unity
  Assets/Scenes/PuzzleScene/HousePuzzleScene/HouseFuseBoxPuzzleScene.unity
  Assets/Scenes/PuzzleScene/HousePuzzleScene/HouseShelfPuzzleScene.unity
  Assets/Script/HouseSceneScript/HouseInteractScript/DaveBoxInteractScript.cs
  Assets/Script/HouseSceneScript/HouseInteractScript/FuseBoxInteractScript.cs
  Assets/Script/HouseSceneScript/HousePuzzleScript/HousePuzzle_ShelfScript/HouseShelfDustScript.cs
  Assets/Script/HouseSceneScript/HousePuzzleScript/HousePuzzle_ShelfScript/HouseShelfPuzzleScript.cs
  Assets/Script/RoomManager.cs
  Assets/Script/UIManager/PrisonUIManager.cs
  Assets/Sprites/OutlineMaterial/HighlightState_HouseScene.mat
  Assets/Sprites/OutlineMaterial/HighlightState_HouseScene.mat.meta
Labels: 👾버그잡기👾, ✨기능구현✨, 🌟리뷰해주세요🌟, 🗿고혁빈🗿, ✅ 완료

#157 [Chore] 파이프 디자인 에셋 적용
  Assets/Resources/PipeBackGround.prefab
  Assets/Resources/PipeBackGround.prefab.meta
  Assets/Resources/PipeTileLshape.prefab
  Assets/Resources/PipeTileStraightShape.prefab
  Assets/Resources/PipeTileTShape.prefab
  Assets/Scenes/PuzzleScene/PrisonPuzzleScene/PrisonPipePuzzleScene.unity
  Assets/Script/PrisonSceneScript/PrisonPuzzleScript/PrisonPuzzle_PipeScript/PrisonPipePuzzleScript.cs
Labels: 🌟리뷰해주세요🌟, 🤓박준우🤓, 🎨스타일수정🎨, ✅ 완료

#158 [Feature] 주택-퍼즐 뒤로가기 버튼 구현
  Assets/Scenes/HouseScene.unity
  Assets/Scenes/PrisonScene.unity
  Assets/Scenes/PuzzleScene/HousePuzzleScene/HouseBlockPuzzleScene.unity
  Assets/Scenes/PuzzleScene/HousePuzzleScene/HouseBookPuzzleScene.unity
  Assets/Scenes/PuzzleScene/HousePuzzleScene/HouseFinalDoorPuzzleScene.unity
  Assets/Scenes/PuzzleScene/HousePuzzleScene/HouseFuseBoxPuzzleScene.unity
  Assets/Scenes/PuzzleScene/HousePuzzleScene/HouseShelfPuzzleScene.unity
  Assets/Scenes/PuzzleScene/HousePuzzleScene/HouseSinkPuzzleScene.unity
  Assets/Scenes/PuzzleScene/HousePuzzleScene/HouseWindowPuzzleScene.unity
  Assets/Scenes/PuzzleScene/PrisonPuzzleScene/PrisonDoorPuzzleScene.unity
  Assets/Scenes/PuzzleScene/PrisonPuzzleScene/PrisonDustPuzzleScene.unity
  Assets/Scenes/PuzzleScene/PrisonPuzzleScene/PrisonLeafPuzzleScene.unity
  Assets/Scenes/PuzzleScene/PrisonPuzzleScene/PrisonPipePuzzleScene.unity
  Assets/Script/HouseSceneScript/HouseInteractScript/BlockInteractScript.cs
  Assets/Script/HouseSceneScript/HouseInteractScript/BookInteractScript.cs
  Assets/Script/HouseSceneScript/HouseInteractScript/FinalDoorInteractScript.cs
  Assets/Script/HouseSceneScript/HouseInteractScript/FuseBoxInteractScript.cs
  Assets/Script/HouseSceneScript/HouseInteractScript/MatthewShelfInteractScript.cs
  Assets/Script/HouseSceneScript/HouseInteractScript/SinkInteractScript.cs
  Assets/Script/HouseSceneScript/HouseInteractScript/WindowInteractScript.cs
  Assets/Script/HouseSceneScript/HousePuzzleScript/HousePuzzle_BlockScript/HouseBlockPuzzleScript.cs
  Assets/Script/HouseSceneScript/HousePuzzleScript/HousePuzzle_BookShelfScript/HouseBookPuzzleScript.cs
  Assets/Script/HouseSceneScript/HousePuzzleScript/HousePuzzle_FinalDoorScript/HouseFinalDoorPuzzleScript.cs
  Assets/Script/HouseSceneScript/HousePuzzleScript/HousePuzzle_FuseBoxScript/HouseFuseBoxPuzzleScript.cs
  Assets/Script/HouseSceneScript/HousePuzzleScript/HousePuzzle_ShelfScript/HouseShelfPuzzleScript.cs
  Assets/Script/HouseSceneScript/HousePuzzleScript/HousePuzzle_SinkScript/HouseSinkPuzzleScript.cs
  Assets/Script/HouseSceneScript/HousePuzzleScript/HousePuzzle_WindowScript/HouseWindowPuzzleScript.cs
  Assets/Script/PauseManager.cs
  Assets/Script/PauseManager.cs.meta
  Assets/Script/PrisonSceneScript/PrisonInteractScript/DoorInteractScript.cs
  Assets/Script/PrisonSceneScript/PrisonInteractScript/DustInteractScript.cs
  Assets/Script/PrisonSceneScript/PrisonInteractScript/LeafInteractScript.cs
  Assets/Script/PrisonSceneScript/PrisonInteractScript/PipeInteractScript.cs
  Assets/Script/UIManager/HouseUIManager.cs
  Assets/Script/UIManager/PrisonUIManager.cs
Labels: ✨기능구현✨, 🎨이진우🎨, ✅ 완료

#163 [Feature] 사운드 에셋 적용하기
  Assets/Audio.meta
  Assets/Audio/ButtonSound.mp3
  Assets/Audio/ButtonSound.mp3.meta
  Assets/Audio/PrisonDoorKey.mp3
  Assets/Audio/PrisonDoorKey.mp3.meta
  Assets/Audio/PrisonDoorKey1.mp3
  Assets/Audio/PrisonDoorKey1.mp3.meta
  Assets/Audio/PrisonDoorKey2.mp3
  Assets/Audio/PrisonDoorKey2.mp3.meta
  Assets/Audio/PrisonDoorKey3.mp3
  Assets/Audio/PrisonDoorKey3.mp3.meta
  Assets/Audio/PrisonDoorOpenSound.mp3
  Assets/Audio/PrisonDoorOpenSound.mp3.meta
  Assets/Audio/PrisonDustLeafSound.mp3
  Assets/Audio/PrisonDustLeafSound.mp3.meta
  Assets/Audio/PrisonSceneBGM.mp3
  Assets/Audio/PrisonSceneBGM.mp3.meta
  Assets/Audio/PrisonSceneDoorPuzzleKeySound1.mp3
  Assets/Audio/PrisonSceneDoorPuzzleKeySound1.mp3.meta
  Assets/Audio/PrisonSceneDoorPuzzleKeySound2.mp3
  Assets/Audio/PrisonSceneDoorPuzzleKeySound2.mp3.meta
  Assets/Audio/PrisonSceneDoorPuzzleKeySound3.mp3
  Assets/Audio/PrisonSceneDoorPuzzleKeySound3.mp3.meta
  Assets/Audio/PrisonSceneDoorPuzzleKeySound4.mp3
  Assets/Audio/PrisonSceneDoorPuzzleKeySound4.mp3.meta
  Assets/Audio/StartLobbyBGM.mp3
  Assets/Audio/StartLobbyBGM.mp3.meta
  Assets/Images/backButton1.png
  Assets/Images/backButton1.png.meta
  Assets/Resources/Player1.prefab
  Assets/Resources/Player2.prefab
  Assets/Scenes/HouseScene.unity
  Assets/Scenes/LobbyScene.unity
  Assets/Scenes/PrisonScene.unity
  Assets/Scenes/PuzzleScene/HousePuzzleScene/HouseBlockPuzzleScene.unity
  Assets/Scenes/PuzzleScene/HousePuzzleScene/HouseBookPuzzleScene.unity
  Assets/Scenes/PuzzleScene/HousePuzzleScene/HouseFinalDoorPuzzleScene.unity
  Assets/Scenes/PuzzleScene/HousePuzzleScene/HouseFuseBoxPuzzleScene.unity
  Assets/Scenes/PuzzleScene/HousePuzzleScene/HouseShelfPuzzleScene.unity
  Assets/Scenes/PuzzleScene/HousePuzzleScene/HouseSinkPuzzleScene.unity
  Assets/Scenes/PuzzleScene/HousePuzzleScene/HouseWindowPuzzleScene.unity
  Assets/Scenes/PuzzleScene/PrisonPuzzleScene/PrisonDoorPuzzleScene.unity
  Assets/Scenes/PuzzleScene/PrisonPuzzleScene/PrisonDustPuzzleScene.unity
  Assets/Scenes/PuzzleScene/PrisonPuzzleScene/PrisonLeafPuzzleScene.unity
  Assets/Scenes/PuzzleScene/PrisonPuzzleScene/PrisonPipePuzzleScene.unity
  Assets/Scenes/RoomScene.unity
  Assets/Scenes/TitleScene.unity
  Assets/Script/AudioManager.meta
  Assets/Script/AudioManager/BGMManager.cs
  Assets/Script/AudioManager/BGMManager.cs.meta
  Assets/Script/AudioManager/SoundAssetManager.cs
  Assets/Script/AudioManager/SoundAssetManager.cs.meta
  Assets/Script/PlayerManager.cs
  Assets/Script/PrisonSceneScript/PrisonInteractScript/DoorInteractScript.cs
  Assets/Script/PrisonSceneScript/PrisonPuzzleScript/PrisonPuzzle_DoorScript/PrisonDoorLockScript.cs
  Assets/Script/PrisonSceneScript/PrisonPuzzleScript/PrisonPuzzle_LeafDustScript/PrisonDustLeafPuzzleScript.cs
  Assets/Script/UIManager/HouseUIManager.cs
  Assets/Script/UIManager/PrisonUIManager.cs
Labels: ✨기능구현✨, 🎨이진우🎨, ✅ 완료

#167 [Chore] 받은 Asset 적용
  Assets/Scenes/HouseScene.unity
  Assets/Scenes/PrisonScene.unity
  Assets/Script/StageManagerScript.cs
Labels: 🎨이진우🎨, 🎨스타일수정🎨, ✅ 완료

#168 [Feature] 스테이지 선택용 단축키 추가 / 마을 씬 플레이어 프리팹화 구현
  Assets/Photon/PhotonUnityNetworking/Resources/PhotonServerSettings.asset
  Assets/Scenes/MapChooseScene.unity
  Assets/Scenes/TitleScene.unity
  Assets/Script/MapChooseSceneScript/MapChooseHouseScript.cs
  Assets/Script/MapChooseSceneScript/MapChoosePrisonScript.cs
  Assets/Script/MapChooseSceneScript/MapChooseSceneScript.cs
  Assets/Script/MapChooseSceneScript/MapChooseSceneScript.cs.meta
  Assets/Script/NetworkingManager.cs
  Assets/Script/UIManager/PrisonUIManager.cs
Labels: ✨기능구현✨, 😖잡일😖, 🗿고혁빈🗿, ✅ 완료

#165 [Fix] 일시정지 관련 버그 일부 해결
  Assets/Scenes/PrisonScene.unity
  Assets/Scenes/RoomScene.unity
  Assets/Script/PlayerManager.cs
  Assets/Script/UIManager/PrisonUIManager.cs
Labels: 👾버그잡기👾, 🌟리뷰해주세요🌟, 🧐도현석🧐, 🤓박준우🤓, ▶️ 진행 중

#171 [Fix] 주택 씬 생성 후 레이어 소팅 관련 문제 해결
  Assets/Scenes/HouseScene.unity
  Assets/Scenes/PrisonScene.unity
  Assets/Scenes/PuzzleScene/HousePuzzleScene/HouseSinkPuzzleScene.unity
  Assets/Scenes/PuzzleScene/HousePuzzleScene/HouseWindowPuzzleScene.unity
  Assets/Script/HouseSceneScript/HouseInteractScript/DaveBoxInteractScript.cs
  Assets/Script/HouseSceneScript/HousePuzzleScript/HousePuzzle_SinkScript/HouseSinkPuzzleScript.cs
  Assets/Script/HouseSceneScript/LayerSortingZoneScript.cs
  Assets/Script/HouseSceneScript/LayerSortingZoneScript.cs.meta
  Assets/Sprites/OutlineMaterial/HighlightState_HouseScene.mat
  Assets/Sprites/Top-Down_Retro_Interior/TopDownHouse_FurnitureState1.png.meta
  Assets/Sprites/Top-Down_Retro_Interior/TopDownHouse_SmallItems.png.meta
Labels: 👾버그잡기👾, ✨기능구현✨, 🌟리뷰해주세요🌟, 🗿고혁빈🗿, ✅ 완료

#170 [Fix] 빠르게 UI 버그 고쳐볼게요
  Assets/Resources/Player1.prefab
  Assets/Resources/Player2.prefab
  Assets/Scenes/HouseScene.unity
  Assets/Scenes/LobbyScene.unity
  Assets/Scenes/PrisonScene.unity
  Assets/Scenes/PuzzleScene/HousePuzzleScene/HouseBlockPuzzleScene.unity
  Assets/Scenes/PuzzleScene/HousePuzzleScene/HouseBookPuzzleScene.unity
  Assets/Scenes/PuzzleScene/HousePuzzleScene/HouseFinalDoorPuzzleScene.unity
  Assets/Scenes/PuzzleScene/HousePuzzleScene/HouseFuseBoxPuzzleScene.unity
  Assets/Scenes/PuzzleScene/HousePuzzleScene/HouseShelfPuzzleScene.unity
  Assets/Scenes/PuzzleScene/HousePuzzleScene/HouseSinkPuzzleScene.unity
  Assets/Scenes/PuzzleScene/HousePuzzleScene/HouseWindowPuzzleScene.unity
  Assets/Scenes/PuzzleScene/PrisonPuzzleScene/PrisonDoorPuzzleScene.unity
  Assets/Scenes/PuzzleScene/PrisonPuzzleScene/PrisonDustPuzzleScene.unity
  Assets/Scenes/PuzzleScene/PrisonPuzzleScene/PrisonLeafPuzzleScene.unity
  Assets/Scenes/PuzzleScene/PrisonPuzzleScene/PrisonPipePuzzleScene.unity
  Assets/Script/AudioManager/BGMManager.cs
  Assets/Script/PrisonSceneScript/PrisonInteractScript/DoorInteractScript.cs
Labels: 🎨이진우🎨, 🎨스타일수정🎨, ✅ 완료

#173 [Fix] 배포 전 버그 픽스
  Assets/Scenes/HouseScene.unity
  Assets/Scenes/MapChooseScene.unity
  Assets/Scenes/PrisonScene.unity
  Assets/Scenes/PuzzleScene/HousePuzzleScene/HouseBlockPuzzleScene.unity
  Assets/Scenes/PuzzleScene/HousePuzzleScene/HouseBookPuzzleScene.unity
  Assets/Scenes/PuzzleScene/HousePuzzleScene/HouseFinalDoorPuzzleScene.unity
  Assets/Scenes/PuzzleScene/HousePuzzleScene/HouseFuseBoxPuzzleScene.unity
  Assets/Scenes/PuzzleScene/HousePuzzleScene/HouseShelfPuzzleScene.unity
  Assets/Scenes/PuzzleScene/HousePuzzleScene/HouseSinkPuzzleScene.unity
  Assets/Scenes/PuzzleScene/HousePuzzleScene/HouseWindowPuzzleScene.unity
  Assets/Scenes/PuzzleScene/PrisonPuzzleScene/PrisonDoorPuzzleScene.unity
  Assets/Scenes/PuzzleScene/PrisonPuzzleScene/PrisonDustPuzzleScene.unity
  Assets/Scenes/PuzzleScene/PrisonPuzzleScene/PrisonLeafPuzzleScene.unity
  Assets/Scenes/PuzzleScene/PrisonPuzzleScene/PrisonPipePuzzleScene.unity
  Assets/Script/StageManagerScript.cs
  Assets/Sprites/TmpHouseImage/HouseSinkPuzzleDirtyPrefab.prefab
  ProjectSettings/TagManager.asset
Labels: 👾버그잡기👾, 😖잡일😖, 🗿고혁빈🗿, ✅ 완료
