Repository pknu-wap/OverClean, pull requests merged in 2024-10, with the labels that each got.

#13 [Feature] 플레이어 이동 구현
  Assets/Code.meta
  Assets/Code/Player.cs
  Assets/Code/Player.cs.meta
  Assets/Sprites.meta
  Assets/Sprites/Farmer 0.png
  Assets/Sprites/Farmer 0.png.meta
Labels: ✨기능구현✨, 🌟리뷰해주세요🌟, 🦭이진우🦭

#15 [Fix] m_DefaultBehaviorMode 변경 및 소소한 에러잡기
  Packages/packages-lock.json
  ProjectSettings/EditorSettings.asset
Labels: 👾버그잡기👾, 😖잡일😖, 🧐도현석🧐

#17 [Chore] 파일 이동, 이름 변경, 남은 에셋 파일 커밋과 같은 잡일들
  Assets/Code.meta
  Assets/Photon/PhotonUnityNetworking/Resources/PhotonServerSettings.asset
  Assets/Resources/billing-mode.json
  Assets/Resources/billing-mode.json.meta
  Assets/Scenes/sample-scene.unity
  Assets/Scenes/sample-scene.unity.meta
  Assets/Script/player.cs
  Assets/Script/player.cs.meta
  Assets/Sprites/farmer-0.png
  Assets/Sprites/farmer-0.png.meta
  ProjectSettings/ProjectSettings.asset
Labels: 😖잡일😖, 🧐도현석🧐

#19 [Feature] 게임 시작 화면 구현하기
  Assets/Resources/BillingMode.json
  Assets/Resources/BillingMode.json.meta
  Assets/Scenes/GameLobby.unity
  Assets/Scenes/GameLobby.unity.meta
  Assets/Scenes/GamePlay.unity
  Assets/Scenes/GamePlay.unity.meta
  Assets/Scenes/MainScreen.unity
  Assets/Scenes/MainScreen.unity.meta
  Assets/Script/Event.cs
  Assets/Script/Event.cs.meta
  Assets/Sprites/overclean_main_screen.jpg
  Assets/Sprites/overclean_main_screen.jpg.meta
  Packages/packages-lock.json
  ProjectSettings/EditorBuildSettings.asset
  ProjectSettings/Packages/com.unity.services.core/Settings.json
  ProjectSettings/SceneTemplateSettings.json
Labels: ✨기능구현✨, 🦭이진우🦭

#22 [Chore] 플레이어 오브젝트 추가하기
  Assets/Animations.meta
  Assets/Animations/Player1.controller
  Assets/Animations/Player1.controller.meta
  Assets/Animations/Run_Player1.anim
  Assets/Animations/Run_Player1.anim.meta
  Assets/Animations/Stand_Player1.anim
  Assets/Animations/Stand_Player1.anim.meta
  Assets/Scenes/GamePlay.unity
  Assets/Script/player.cs
  Packages/manifest.json
  Packages/packages-lock.json
Labels: ✨기능구현✨, 😖잡일😖, 🦭이진우🦭

#26 [Feature] Exit 눌렀을때 모달창 띄우기
  Assets/Fonts.meta
  Assets/Fonts/Jua-Regular.ttf
  Assets/Fonts/Jua-Regular.ttf.meta
  Assets/Fonts/Maplestory Light.ttf
  Assets/Fonts/Maplestory Light.ttf.meta
  Assets/Scenes/MainScreen.unity
  Packages/manifest.json
  Packages/packages-lock.json
Labels: ✨기능구현✨, 🌟리뷰해주세요🌟, 🦭이진우🦭

#37 [Fix] Assets/private 폴더가 자꾸 수정사항에 추적되는 오류 수정
  .gitignore
Labels: 👾버그잡기👾, 😖잡일😖, 🗿고혁빈🗿

#31 [Feature] 랜덤 방 입장 매치메이킹 기능 구현
  .gitignore
  Assets/Scenes/GameLobby.unity
  Assets/Scenes/MainScreen.unity
  Assets/Scenes/MakeRoom.unity
  Assets/Script/LobbyManager.cs
  Assets/Script/LobbyManager.cs.meta
  Assets/Script/NetworkingManager.cs
  Assets/Script/NetworkingManager.cs.meta
  Assets/Script/RoomManager.cs
  Assets/Script/RoomManager.cs.meta
  ProjectSettings/UnityConnectSettings.asset
Labels: ✨기능구현✨, 🌟리뷰해주세요🌟, 🧐도현석🧐

#40 [Feature] 카메라 분할뷰 구현하기
  Assets/Scenes/GamePlay.unity
  Assets/Scenes/PrisonScene.unity
  Assets/Script/player.cs
  ProjectSettings/InputManager.asset
Labels: ✨기능구현✨, 🌟리뷰해주세요🌟, 🦭이진우🦭

#46 [Style] 게임 메인 화면 이미지 수정
  Assets/Scenes/GamePlay.unity.meta
  Assets/Scenes/MainScreen.unity
Labels: 🌟리뷰해주세요🌟, 🦭이진우🦭, 🎨스타일수정🎨

#47 [Feature] 튜토리얼 내 미니게임 씬 창 구현
  Assets/Scenes/PrisonScene.unity
  Assets/Scenes/PuzzleScene.meta
  Assets/Scenes/PuzzleScene/PrisonPuzzleScene.meta
  Assets/Scenes/PuzzleScene/PrisonPuzzleScene/PrisonDoorPuzzleScene.unity
  Assets/Scenes/PuzzleScene/PrisonPuzzleScene/PrisonDoorPuzzleScene.unity.meta
  Assets/Scenes/PuzzleScene/PrisonPuzzleScene/PrisonDustPuzzleScene.unity
  Assets/Scenes/PuzzleScene/PrisonPuzzleScene/PrisonDustPuzzleScene.unity.meta
  Assets/Scenes/PuzzleScene/PrisonPuzzleScene/PrisonLeafPuzzleScene.unity
  Assets/Scenes/PuzzleScene/PrisonPuzzleScene/PrisonLeafPuzzleScene.unity.meta
  Assets/Scenes/PuzzleScene/PrisonPuzzleScene/PrisonPipePuzzleScene.unity
  Assets/Scenes/PuzzleScene/PrisonPuzzleScene/PrisonPipePuzzleScene.unity.meta
  Assets/Script/PrisonInteractScript/DoorInteractScript.cs
  Assets/Script/PrisonInteractScript/DustInteractScript.cs
  Assets/Script/PrisonInteractScript/LeafInteractScript.cs
  Assets/Script/PrisonInteractScript/PipeInteractScript.cs
  Assets/Script/PrisonInteractScript/PipeInteractZoneScript.cs
  Assets/Script/PrisonPuzzleScript.meta
  Assets/Script/PrisonPuzzleScript/PUZZLETESTSCRIPT.cs
  Assets/Script/PrisonPuzzleScript/PUZZLETESTSCRIPT.cs.meta
  Assets/Script/PrisonPuzzleScript/PrisonDoorPuzzleScript.cs
  Assets/Script/PrisonPuzzleScript/PrisonDoorPuzzleScript.cs.meta
  Assets/Script/PrisonPuzzleScript/PrisonDustPuzzleScript.cs
  Assets/Script/PrisonPuzzleScript/PrisonDustPuzzleScript.cs.meta
  Assets/Script/PrisonPuzzleScript/PrisonLeafPuzzleScript.cs
  Assets/Script/PrisonPuzzleScript/PrisonLeafPuzzleScript.cs.meta
  Assets/Script/PrisonPuzzleScript/PrisonPipePuzzleScript.cs
  Assets/Script/PrisonPuzzleScript/PrisonPipePuzzleScript.cs.meta
  Assets/Sprites/PuzzleCameraRenderTexture.renderTexture
  Assets/Sprites/PuzzleCameraRenderTexture.renderTexture.meta
  ProjectSettings/EditorBuildSettings.asset
Labels: ✨기능구현✨, 🌟리뷰해주세요🌟, 🗿고혁빈🗿

#49 [Feature] 코드 입력을 통한 방 입장 구현하기
  Assets/Photon/PhotonUnityNetworking/Resources/PhotonServerSettings.asset
  Assets/Scenes/GameLobby.unity
  Assets/Scenes/MainScreen.unity
  Assets/Scenes/Room.unity
  Assets/Script/LobbyManager.cs
  Assets/Script/NetworkingManager.cs
  Assets/Script/RoomManager.cs
  Assets/TextMesh Pro/Resources/Fonts & Materials/LiberationSans SDF - Fallback.asset
  Assets/TextMesh Pro/Resources/Fonts & Materials/LiberationSans SDF.asset
Labels: ✨기능구현✨, 🌟리뷰해주세요🌟, 🧐도현석🧐

#51 [Fix] 이전 Merge에서 일어난 오류 수정
  Assets/Scenes/PrisonScene.unity
  Assets/Scenes/PuzzleScene/PrisonPuzzleScene/PrisonDoorPuzzleScene.unity
  Assets/Scenes/PuzzleScene/PrisonPuzzleScene/PrisonDoorPuzzleScene.unity.meta
  Assets/Scenes/PuzzleScene/PrisonPuzzleScene/PrisonDustPuzzleScene.unity
  Assets/Scenes/PuzzleScene/PrisonPuzzleScene/PrisonLeafPuzzleScene.unity
  Assets/Scenes/PuzzleScene/PrisonPuzzleScene/PrisonPipePuzzleScene.unity
  ProjectSettings/TagManager.asset
Labels: 👾버그잡기👾, 🌟리뷰해주세요🌟, 🗿고혁빈🗿

#53 [Feature] 2인용 퍼즐 시작 가능 조건 시각화 구현
  Assets/Scenes/PrisonScene.unity
  Assets/Script/PrisonInteractScript/PipeInteractZoneScript.cs
Labels: ✨기능구현✨, 🌟리뷰해주세요🌟, 🗿고혁빈🗿

#58 [Fix] 감옥 문 테두리 깨짐현상 수정
  Assets/Scenes/PrisonScene.unity
  Assets/SpriteOutline/Shaders/SpriteOutline.shader
  Assets/Sprites/OutlineMaterial/DoorInteractShader.shader
  Assets/Sprites/OutlineMaterial/DoorInteractShader.shader.meta
  Assets/Sprites/OutlineMaterial/HighlightState_Door.mat
  Assets/Sprites/OutlineMaterial/HighlightState_Door.mat.meta
  Assets/Sprites/OutlineMaterial/HighlightState_ElseObject.mat
  Assets/Sprites/OutlineMaterial/HighlightState_ElseObject.mat.meta
Labels: 👾버그잡기👾, ✨기능구현✨, 🌟리뷰해주세요🌟, 🗿고혁빈🗿

#59 [Feature] 인게임UI 상단바 구현하기
  Assets/Scenes/PrisonScene.unity
Labels: ✨기능구현✨, 🎨이진우🎨, 🎨스타일수정🎨

#61 [Feature] 자물쇠 퍼즐 구현 / 싱글톤 퍼즐 매니저 구현
  Assets/Scenes/PrisonScene.unity
  Assets/Scenes/PuzzleScene/PrisonPuzzleScene/PrisonDoorPuzzleScene.unity
  Assets/Script/PrisonInteractScript/DoorInteractScript.cs
  Assets/Script/PrisonPuzzleScript/PrisonDoorPuzzleScript.cs
  Assets/Script/PrisonPuzzleScript/PrisonPuzzle_DoorScript.meta
  Assets/Script/PrisonPuzzleScript/PrisonPuzzle_DoorScript/PrisonDoorKeyScript.cs
  Assets/Script/PrisonPuzzleScript/PrisonPuzzle_DoorScript/PrisonDoorKeyScript.cs.meta
  Assets/Script/PrisonPuzzleScript/PrisonPuzzle_DoorScript/PrisonDoorLockScript.cs
  Assets/Script/PrisonPuzzleScript/PrisonPuzzle_DoorScript/PrisonDoorLockScript.cs.meta
  Assets/Script/PrisonPuzzleScript/PrisonPuzzle_DoorScript/PrisonDoorPuzzleScript.cs
  Assets/Script/PrisonPuzzleScript/PrisonPuzzle_DoorScript/PrisonDoorPuzzleScript.cs.meta
  Assets/Script/PuzzleManager.cs
  Assets/Script/PuzzleManager.cs.meta
  Assets/Sprites/PuzzleCameraRenderTexture.renderTexture
  Assets/Sprites/TmpLockKeySprite.meta
  Assets/Sprites/TmpLockKeySprite/TmpKeya.png
  Assets/Sprites/TmpLockKeySprite/TmpKeya.png.meta
  Assets/Sprites/TmpLockKeySprite/TmpKeya.prefab
  Assets/Sprites/TmpLockKeySprite/TmpKeya.prefab.meta
  Assets/Sprites/TmpLockKeySprite/TmpKeyb.png
  Assets/Sprites/TmpLockKeySprite/TmpKeyb.png.meta
  Assets/Sprites/TmpLockKeySprite/TmpKeyb.prefab
  Assets/Sprites/TmpLockKeySprite/TmpKeyb.prefab.meta
  Assets/Sprites/TmpLockKeySprite/TmpKeyc.png
  Assets/Sprites/TmpLockKeySprite/TmpKeyc.png.meta
  Assets/Sprites/TmpLockKeySprite/TmpKeyc.prefab
  Assets/Sprites/TmpLockKeySprite/TmpKeyc.prefab.meta
  Assets/Sprites/TmpLockKeySprite/TmpKeyd.png
  Assets/Sprites/TmpLockKeySprite/TmpKeyd.png.meta
  Assets/Sprites/TmpLockKeySprite/TmpKeyd.prefab
  Assets/Sprites/TmpLockKeySprite/TmpKeyd.prefab.meta
  Assets/Sprites/TmpLockKeySprite/TmpKeye.png
  Assets/Sprites/TmpLockKeySprite/TmpKeye.png.meta
  Assets/Sprites/TmpLockKeySprite/TmpKeye.prefab
  Assets/Sprites/TmpLockKeySprite/TmpKeye.prefab.meta
  Assets/Sprites/TmpLockKeySprite/TmpLockA.png
  Assets/Sprites/TmpLockKeySprite/TmpLockA.png.meta
  Assets/Sprites/TmpLockKeySprite/TmpLockA.prefab
  Assets/Sprites/TmpLockKeySprite/TmpLockA.prefab.meta
  Assets/Sprites/TmpLockKeySprite/TmpLockB.png
  Assets/Sprites/TmpLockKeySprite/TmpLockB.png.meta
  Assets/Sprites/TmpLockKeySprite/TmpLockB.prefab
  Assets/Sprites/TmpLockKeySprite/TmpLockB.prefab.meta
  Assets/Sprites/TmpLockKeySprite/TmpLockC.png
  Assets/Sprites/TmpLockKeySprite/TmpLockC.png.meta
  Assets/Sprites/TmpLockKeySprite/TmpLockC.prefab
  Assets/Sprites/TmpLockKeySprite/TmpLockC.prefab.meta
  ProjectSettings/TagManager.asset
Labels: 👾버그잡기👾, ✨기능구현✨, 🌟리뷰해주세요🌟, 🗿고혁빈🗿, ✅ 완료

#63 [Feature] 메인화면에서 Exit버튼 누르면 모달창 나오게 구현
  Assets/Scenes/MainScreen.unity
  Assets/Script/NetworkingManager.cs
Labels: 🌟리뷰해주세요🌟, 🎨이진우🎨, ✅ 완료

#67 [Fix] 문 스프라이트 도트 깨짐현상 해결
  Assets/Scenes/PrisonScene.unity
  Assets/Sprites/OutlineMaterial/HighlightState_Door.mat
Labels: 👾버그잡기👾, 🌟리뷰해주세요🌟, 🗿고혁빈🗿, 🎨스타일수정🎨, ✅ 완료

#69 [Feature] 룸에서 플레이어 캐릭터 할당 및 전환, Ready 시 Scene 전환 구현
  Assets/Images/tempImage.png
  Assets/Images/tempImage.png.meta
  Assets/Photon/PhotonUnityNetworking/Resources/PhotonServerSettings.asset
  Assets/Scenes/Room.unity
  Assets/Script/NetworkingManager.cs
  Assets/Script/RoomManager.cs
  Assets/Script/UIManager.cs
  Assets/Script/UIManager.cs.meta
  ProjectSettings/EditorBuildSettings.asset
Labels: ✨기능구현✨, 🌟리뷰해주세요🌟, 🧐도현석🧐, ✅ 완료

#75 [Feature] 퍼즐 중복 로드 방지 / 상호작용 중 플레이어 이동 제한 구현
  Assets/Scenes/PrisonScene.unity
  Assets/Script/PrisonInteractScript/DoorInteractScript.cs
  Assets/Script/PrisonInteractScript/DustInteractScript.cs
  Assets/Script/PrisonInteractScript/LeafInteractScript.cs
  Assets/Script/PrisonInteractScript/PipeInteractScript.cs
  Assets/Script/StageManagerScript.cs
  Assets/Script/player.cs
Labels: ✨기능구현✨, 🌟리뷰해주세요🌟, 🗿고혁빈🗿, ✅ 완료

#79 [Feature] 파이프 퍼즐 그리드 화면 구성, 파이프 회전 함수 구현
  Assets/Scenes/PuzzleScene/PrisonPuzzleScene/PrisonPipePuzzleScene.unity
  Assets/Script/PrisonPuzzleScript/PrisonPipePuzzleScript.cs
  Assets/Script/PrisonPuzzleScript/PrisonPuzzle_PipeScript.meta
  Assets/Script/PrisonPuzzleScript/PrisonPuzzle_PipeScript/PipeTileScript.cs
  Assets/Script/PrisonPuzzleScript/PrisonPuzzle_PipeScript/PipeTileScript.cs.meta
  Assets/Script/PrisonPuzzleScript/PrisonPuzzle_PipeScript/PrisonPipePuzzleScript.cs
  Assets/Script/PrisonPuzzleScript/PrisonPuzzle_PipeScript/PrisonPipePuzzleScript.cs.meta
  Assets/Sprites/TmpPipeTileSprite.meta
  Assets/Sprites/TmpPipeTileSprite/PipeTileLShape.png
  Assets/Sprites/TmpPipeTileSprite/PipeTileLShape.png.meta
  Assets/Sprites/TmpPipeTileSprite/PipeTileLshape.prefab
  Assets/Sprites/TmpPipeTileSprite/PipeTileLshape.prefab.meta
  Assets/Sprites/TmpPipeTileSprite/PipeTileStraightShape.png
  Assets/Sprites/TmpPipeTileSprite/PipeTileStraightShape.png.meta
  Assets/Sprites/TmpPipeTileSprite/PipeTileStraightShape.prefab
  Assets/Sprites/TmpPipeTileSprite/PipeTileStraightShape.prefab.meta
  Assets/Sprites/TmpPipeTileSprite/PipeTileTShape.png
  Assets/Sprites/TmpPipeTileSprite/PipeTileTShape.png.meta
  Assets/Sprites/TmpPipeTileSprite/PipeTileTshape.prefab
  Assets/Sprites/TmpPipeTileSprite/PipeTileTshape.prefab.meta
Labels: ✨기능구현✨, 🤓박준우🤓, ✅ 완료

#89 [Feature] 먼지, 낙엽 퍼즐 에셋 적용 / 성공 시 체크표시 구현
  Assets/Scenes/PrisonScene.unity
  Assets/Scenes/PuzzleScene/PrisonPuzzleScene/PrisonDustPuzzleScene.unity
  Assets/Scenes/PuzzleScene/PrisonPuzzleScene/PrisonLeafPuzzleScene.unity
  Assets/Script/PrisonPuzzleScript/PrisonPuzzle_LeafDustScript/PrisonDustLeafDestinationAreaScript.cs
  Assets/Script/PrisonPuzzleScript/PrisonPuzzle_LeafDustScript/PrisonDustLeafPuzzleScript.cs
  Assets/Sprites/PrisonDoorPuzzlePrefab.meta
  Assets/Sprites/PrisonDoorPuzzlePrefab/KeyPrefab1.prefab
  Assets/Sprites/PrisonDoorPuzzlePrefab/KeyPrefab1.prefab.meta
  Assets/Sprites/PrisonDoorPuzzlePrefab/KeyPrefab2.prefab
  Assets/Sprites/PrisonDoorPuzzlePrefab/KeyPrefab2.prefab.meta
  Assets/Sprites/PrisonDoorPuzzlePrefab/KeyPrefab3.prefab
  Assets/Sprites/PrisonDoorPuzzlePrefab/KeyPrefab3.prefab.meta
  Assets/Sprites/PrisonDoorPuzzlePrefab/KeyPrefab4.prefab
  Assets/Sprites/PrisonDoorPuzzlePrefab/KeyPrefab4.prefab.meta
  Assets/Sprites/PrisonDoorPuzzlePrefab/KeyPrefab5.prefab
  Assets/Sprites/PrisonDoorPuzzlePrefab/KeyPrefab5.prefab.meta
  Assets/Sprites/PrisonDoorPuzzlePrefab/LockPrefab1.prefab
  Assets/Sprites/PrisonDoorPuzzlePrefab/LockPrefab1.prefab.meta
  Assets/Sprites/PrisonDoorPuzzlePrefab/LockPrefab2.prefab
  Assets/Sprites/PrisonDoorPuzzlePrefab/LockPrefab2.prefab.meta
  Assets/Sprites/PrisonDoorPuzzlePrefab/LockPrefab3.prefab
  Assets/Sprites/PrisonDoorPuzzlePrefab/LockPrefab3.prefab.meta
  Assets/Sprites/PrisonDoorPuzzlePrefab/LockPrefab4.prefab
  Assets/Sprites/PrisonDoorPuzzlePrefab/LockPrefab4.prefab.meta
  Assets/Sprites/PrisonDoorPuzzlePrefab/LockPrefab5.prefab
  Assets/Sprites/PrisonDoorPuzzlePrefab/LockPrefab5.prefab.meta
  Assets/Sprites/PrisonLeafDustPuzzlePrefab.meta
  Assets/Sprites/PrisonLeafDustPuzzlePrefab/DustPrefab1.prefab
  Assets/Sprites/PrisonLeafDustPuzzlePrefab/DustPrefab1.prefab.meta
  Assets/Sprites/PrisonLeafDustPuzzlePrefab/DustPrefab2.prefab
  Assets/Sprites/PrisonLeafDustPuzzlePrefab/DustPrefab2.prefab.meta
  Assets/Sprites/PrisonLeafDustPuzzlePrefab/DustPrefab3.prefab
  Assets/Sprites/PrisonLeafDustPuzzlePrefab/DustPrefab3.prefab.meta
  Assets/Sprites/PrisonLeafDustPuzzlePrefab/LeafPrefab1.prefab
  Assets/Sprites/PrisonLeafDustPuzzlePrefab/LeafPrefab1.prefab.meta
  Assets/Sprites/PrisonLeafDustPuzzlePrefab/LeafPrefab2.prefab
  Assets/Sprites/PrisonLeafDustPuzzlePrefab/LeafPrefab2.prefab.meta
  Assets/Sprites/PrisonLeafDustPuzzlePrefab/LeafPrefab3.prefab
  Assets/Sprites/PrisonLeafDustPuzzlePrefab/LeafPrefab3.prefab.meta
  Assets/Sprites/PrisonLeafDustPuzzlePrefab/LeafPrefab4.prefab
  Assets/Sprites/PrisonLeafDustPuzzlePrefab/LeafPrefab4.prefab.meta
  Assets/Sprites/TmpDustLeafSprite/TmpDust.png
  Assets/Sprites/TmpDustLeafSprite/TmpDust.png.meta
  Assets/Sprites/TmpDustLeafSprite/TmpDust2.png
  Assets/Sprites/TmpDustLeafSprite/TmpDust2.png.meta
  Assets/Sprites/TmpDustLeafSprite/TmpDust3.png
  Assets/Sprites/TmpDustLeafSprite/TmpDust3.png.meta
  Assets/Sprites/TmpDustLeafSprite/TmpLeaf.png
  Assets/Sprites/TmpDustLeafSprite/TmpLeaf.png.meta
  Assets/Sprites/TmpDustLeafSprite/TmpLeaf2.png
  Assets/Sprites/TmpDustLeafSprite/TmpLeaf2.png.meta
  Assets/Sprites/TmpDustLeafSprite/TmpLeaf3.png
  Assets/Sprites/TmpDustLeafSprite/TmpLeaf3.png.meta
  Assets/Sprites/TmpOImage.png
  Assets/Sprites/TmpOImage.png.meta
  Assets/Sprites/TmpXImage.png
  Assets/Sprites/TmpXImage.png.meta
Labels: ✨기능구현✨, 🗿고혁빈🗿, 🎨스타일수정🎨, ✅ 완료

#81 [Chore] 씬, 오브젝트 이름 변경
  Assets/Scenes/GamePlay.unity
  Assets/Scenes/GamePlay.unity.meta
  Assets/Scenes/LobbyScene.unity
  Assets/Scenes/LobbyScene.unity.meta
  Assets/Scenes/RoomScene.unity
  Assets/Scenes/RoomScene.unity.meta
  Assets/Scenes/TitleScene.unity
  Assets/Scenes/TitleScene.unity.meta
  Assets/Script/NetworkingManager.cs
  Assets/Script/RoomManager.cs
  ProjectSettings/EditorBuildSettings.asset
Labels: 😖잡일😖, 🧐도현석🧐, ✅ 완료

#91 [Docs] 그라운드 룰 & 개발 일정 이미지 변경
  README.md
Labels: 📝문서📝, 🎨이진우🎨, ✅ 완료
